services:
  - type: web
    name: thegivingcircle
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 